AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sendmail-app
  
  Sample SAM Template for sendmail-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  SendmailFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: main
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sendmail
            Method: POST
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          ReCAPTCHA_SECRET: 'reCaptcha Secret Key'
          SES_REGION: 'us-west-1'
          MAIL_SUBJECT: 'Test email'
          IS_HTML: true
          MAIL_FROM: 'info@example.com'
          CC_ADDRESSES: '<ccAddresses@example.com>, Bob <bob@example.com>'
          BCC_ADDRESSES: '<bccAddresses@example.com>, Bob <bob@example.com>'
          TO_ADDRESSES: '<toAddresses@example.com>, Bob <bob@example.com>'
          SMTP_USER: 'no-reply@e-business.co.jp'
          SMTP_PASSWORD: 'password'
          SMTP_HOST: 'sender.com'
          SMTP_PORT: '587'
  